2017-04-28 14:48:39,224 ERROR 29331 [-/127.0.0.1/-/5ms GET /] nodejs.Error: Please set config.keys first
    at Application.get keys [as keys] (/Users/liudong/Documents/website/8jk/node_modules/._egg@1.1.0@egg/lib/application.js:181:15)
    at Object.get cookies [as cookies] (/Users/liudong/Documents/website/8jk/node_modules/._egg@1.1.0@egg/app/extend/context.js:17:65)
    at Object.get [egg-security#CSRF_SECRET] (/Users/liudong/Documents/website/8jk/node_modules/._egg-security@1.9.0@egg-security/app/extend/context.js:76:32)
    at Object.ensureCsrfSecret (/Users/liudong/Documents/website/8jk/node_modules/._egg-security@1.9.0@egg-security/app/extend/context.js:87:13)
    at Object.csrf (/Users/liudong/Documents/website/8jk/node_modules/._egg-security@1.9.0@egg-security/lib/middlewares/csrf.js:13:10)
    at next (native)
    at Object.<anonymous> (/Users/liudong/Documents/website/8jk/node_modules/._koa-compose@2.5.1@koa-compose/index.js:28:19)
    at next (native)
    at onFulfilled (/Users/liudong/Documents/website/8jk/node_modules/._co@4.6.0@co/index.js:65:19)
    at /Users/liudong/Documents/website/8jk/node_modules/._co@4.6.0@co/index.js:54:5

pid: 29331
hostname: liud.local

2017-04-28 14:48:39,451 ERROR 29331 [-/127.0.0.1/-/2ms GET /apple-touch-icon-precomposed.png] nodejs.Error: Please set config.keys first
    at Application.get keys [as keys] (/Users/liudong/Documents/website/8jk/node_modules/._egg@1.1.0@egg/lib/application.js:181:15)
    at Object.get cookies [as cookies] (/Users/liudong/Documents/website/8jk/node_modules/._egg@1.1.0@egg/app/extend/context.js:17:65)
    at Object.get [egg-security#CSRF_SECRET] (/Users/liudong/Documents/website/8jk/node_modules/._egg-security@1.9.0@egg-security/app/extend/context.js:76:32)
    at Object.ensureCsrfSecret (/Users/liudong/Documents/website/8jk/node_modules/._egg-security@1.9.0@egg-security/app/extend/context.js:87:13)
    at Object.csrf (/Users/liudong/Documents/website/8jk/node_modules/._egg-security@1.9.0@egg-security/lib/middlewares/csrf.js:13:10)
    at next (native)
    at Object.<anonymous> (/Users/liudong/Documents/website/8jk/node_modules/._koa-compose@2.5.1@koa-compose/index.js:28:19)
    at next (native)
    at onFulfilled (/Users/liudong/Documents/website/8jk/node_modules/._co@4.6.0@co/index.js:65:19)
    at /Users/liudong/Documents/website/8jk/node_modules/._co@4.6.0@co/index.js:54:5

pid: 29331
hostname: liud.local

2017-04-28 14:48:39,469 ERROR 29331 [-/127.0.0.1/-/1ms GET /apple-touch-icon.png] nodejs.Error: Please set config.keys first
    at Application.get keys [as keys] (/Users/liudong/Documents/website/8jk/node_modules/._egg@1.1.0@egg/lib/application.js:181:15)
    at Object.get cookies [as cookies] (/Users/liudong/Documents/website/8jk/node_modules/._egg@1.1.0@egg/app/extend/context.js:17:65)
    at Object.get [egg-security#CSRF_SECRET] (/Users/liudong/Documents/website/8jk/node_modules/._egg-security@1.9.0@egg-security/app/extend/context.js:76:32)
    at Object.ensureCsrfSecret (/Users/liudong/Documents/website/8jk/node_modules/._egg-security@1.9.0@egg-security/app/extend/context.js:87:13)
    at Object.csrf (/Users/liudong/Documents/website/8jk/node_modules/._egg-security@1.9.0@egg-security/lib/middlewares/csrf.js:13:10)
    at next (native)
    at Object.<anonymous> (/Users/liudong/Documents/website/8jk/node_modules/._koa-compose@2.5.1@koa-compose/index.js:28:19)
    at next (native)
    at onFulfilled (/Users/liudong/Documents/website/8jk/node_modules/._co@4.6.0@co/index.js:65:19)
    at /Users/liudong/Documents/website/8jk/node_modules/._co@4.6.0@co/index.js:54:5

pid: 29331
hostname: liud.local

2017-04-28 22:13:03,565 ERROR 29330 nodejs.ClusterClientNoResponseError: client no response in 3608631ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/liudong/Documents/website/8jk/node_modules/._cluster-client@1.6.3@cluster-client/lib/leader.js:71:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 29330
hostname: liud.local

2017-04-28 23:13:22,012 ERROR 29330 nodejs.ClusterClientNoResponseError: client no response in 3607427ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/liudong/Documents/website/8jk/node_modules/._cluster-client@1.6.3@cluster-client/lib/leader.js:71:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 29330
hostname: liud.local

2017-04-29 00:13:41,559 ERROR 29330 nodejs.ClusterClientNoResponseError: client no response in 3609395ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/liudong/Documents/website/8jk/node_modules/._cluster-client@1.6.3@cluster-client/lib/leader.js:71:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 29330
hostname: liud.local

2017-04-29 01:14:00,594 ERROR 29330 nodejs.ClusterClientNoResponseError: client no response in 3608372ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/liudong/Documents/website/8jk/node_modules/._cluster-client@1.6.3@cluster-client/lib/leader.js:71:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 29330
hostname: liud.local

2017-04-29 02:14:18,986 ERROR 29330 nodejs.ClusterClientNoResponseError: client no response in 3607268ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/liudong/Documents/website/8jk/node_modules/._cluster-client@1.6.3@cluster-client/lib/leader.js:71:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 29330
hostname: liud.local

2017-04-29 03:14:36,874 ERROR 29330 nodejs.ClusterClientNoResponseError: client no response in 3607242ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/liudong/Documents/website/8jk/node_modules/._cluster-client@1.6.3@cluster-client/lib/leader.js:71:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 29330
hostname: liud.local

2017-04-29 04:14:54,883 ERROR 29330 nodejs.ClusterClientNoResponseError: client no response in 3607424ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/liudong/Documents/website/8jk/node_modules/._cluster-client@1.6.3@cluster-client/lib/leader.js:71:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 29330
hostname: liud.local

2017-04-29 05:15:12,584 ERROR 29330 nodejs.ClusterClientNoResponseError: client no response in 3607564ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/liudong/Documents/website/8jk/node_modules/._cluster-client@1.6.3@cluster-client/lib/leader.js:71:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 29330
hostname: liud.local

2017-04-29 06:13:25,896 ERROR 29330 nodejs.ClusterClientNoResponseError: client no response in 3482222ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/liudong/Documents/website/8jk/node_modules/._cluster-client@1.6.3@cluster-client/lib/leader.js:71:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 29330
hostname: liud.local

2017-05-02 08:27:38,181 ERROR 29330 nodejs.ClusterClientNoResponseError: client no response in 267242227ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/liudong/Documents/website/8jk/node_modules/._cluster-client@1.6.3@cluster-client/lib/leader.js:71:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 29330
hostname: liud.local

2017-05-02 08:59:05,917 ERROR 29330 nodejs.ClusterClientNoResponseError: client no response in 1797528ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/liudong/Documents/website/8jk/node_modules/._cluster-client@1.6.3@cluster-client/lib/leader.js:71:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 29330
hostname: liud.local

2017-05-02 09:04:21,845 ERROR 29330 nodejs.ClusterClientNoResponseError: client no response in 215875ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/liudong/Documents/website/8jk/node_modules/._cluster-client@1.6.3@cluster-client/lib/leader.js:71:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 29330
hostname: liud.local

